### ISSUE TITLE
Make Sort order configurable

### ISSUE THREAD

**Issue by cbleek** [yawik/Solr#20]
Currently, the sort order is [hardcoded](https://github.com/yawik/Solr/blob/master/src/Filter/JobBoardPaginationQuery.php#L64)  descending by date.

We want to make this configurable. For example this would make the 

<             $randString = rand(1,100); 
<             $query->addSortField('random'.$randString, SolrQuery::ORDER_DESC);

**Comment by TiSiE** [comment]
The configurable sort order should only be applied when an "empty search" is performed.
https://github.com/yawik/Solr/blob/90177bc429571e6628676add488da079fa505908/src/Filter/JobBoardPaginationQuery.php#L62-L65

Analogous to #19, there should be an array value in the ModuleOptions to allow specifiying one or more sort orders. The currently harcoded one should stay the default choice, if nothing is configured.

Possible options array could be
``` php
[
    'fieldName' => SolrQuery::ORDER_ASC,
    'secondField' => SolrQuery::ORDER_DESC,
];
```

or an array of arrays
``` php
[
    ['fieldName', SolrQuery::ORDER_ASC],
]
```

**Comment by TiSiE** [comment]
@kilip It would be great if you could do it.

Please note, that the default branch was changed to 'master'
