### ISSUE TITLE
Use viewHelper, when storing location in solr

### ISSUE THREAD

**Issue by cbleek** [yawik/Solr#28]
can we use our new [viewHelper](https://github.com/cross-solution/YAWIK/blob/master/module/Core/src/View/Helper/FormatLocation.php) when saving the "location" in solr?

The value, which is stored in Solr:

![Solr-solcation](https://user-images.githubusercontent.com/858642/84536678-a3e35500-acee-11ea-8977-d01354f75015.png)

https://github.com/yawik/Solr/blob/master/src/Entity/JobProxy.php#L358

**Comment by cbleek** [comment]
Yawik stores locations as an array of objects.
```
> db.jobs.find({_id:ObjectId("5c8115410acec3d470a03e41")},{locations:1}).pretty();
{
        "_id" : ObjectId("5c8115410acec3d470a03e41"),
        "locations" : [
                {
                        "city" : "Vechta",
                        "region" : "Niedersachsen",
                        "coordinates" : {
                                "type" : "Point",
                                "coordinates" : [
                                        8.28598,
                                        52.72632
                                ],
                                "_entity" : "Geo\\Entity\\Geometry\\Point"
                        }
                }
        ]
}
```

Solr/blob/master/src/Entity/JobProxy.php#L358 stores a location by simply:

```
    /**
     * @see \Jobs\Entity\JobInterface::setLocation()
     */
    public function setLocation($location)
    {
        return $this->job->setLocation($location);
    }
```
the location field in solr is a sting. After saving a job in our demo, the location in solr contains "location":"Vechta, Niedersachsen ( 8.28598, 52.72632 )",

**Comment by TiSiE** [comment]
Problem is in another module (yawik/DemoSkin)
