### ISSUE TITLE
Frage zu Facet Queries

### ISSUE THREAD

**Issue by StefanieD** [yawik/Solr#30]
Hallo,

ist es momentan möglich Facet Queries zu nutzen?

**Ich hatte folgendes Szenario:**
Ich wollte neben den Standard-Filtern einen Filter haben, der die Jobs nach dem publishDate filtert. Dazu sollen aber Filterqueries genutzt werden. In meinem Fall sieht es z.b. so aus:

```
$query->addFacetQuery('datePublishStart:[NOW-1DAY TO NOW]') // 24h
            ->addFacetQuery('datePublishStart:[NOW-3DAYS TO NOW]') // 3 Tage
            ->addFacetQuery('datePublishStart:[NOW-7DAYS TO NOW]') // 7 Tage
            ->addFacetQuery('datePublishStart:[NOW-30DAYS TO NOW]'); // 30 Tage
```

Ich habe als Lösung die Klasse \Solr\Facets erweitert, um auch Facet Queries auszulesen. 

Facets Fields können ja momentan über die Konfigurationsdatei definiert werden. Ist das für Queries auch geplant?

VG Stefanie Drost

**Comment by TiSiE** [comment]
Es ist zur Zeit möglich, zusätzliche FilterQueries zu konfigurieren.
Dazu erstellt man ein Array in der ModulOptions-Konfiguration mit dem Key `filterQueries`.
Diese werden dann im [JobboardPaginator-Query-Filter](https://github.com/yawik/Solr/blob/master/src/Filter/JobBoardPaginationQuery.php#L188) verarbeitet.

Auf ähnliche Weise könnte man auch zusätzliche Facet-Queries einbauen.
Geplant ist das allerdings momentan nicht - ein entsprechender Pull-Request wird aber garantiert beachtet werden.
