### ISSUE TITLE
 make this module ZF3 compatible 

### ISSUE THREAD

**Issue by cbleek** [yawik/Solr#5]
Docs: http://yawik.readthedocs.io/en/latest/modules/solr/index.html

**Comment by cbleek** [comment]
latest [commit](https://github.com/yawik/Solr/commit/3b1b6b739b5317c14b9ab70bbf8131fc327f1d38) requires a "*_MultiString" field in the solr index.

![auswahl_999 517](https://user-images.githubusercontent.com/858642/30262781-90a061f2-96d2-11e7-8c1b-6daeb6819b53.png)

**Comment by kilip** [comment]
Hi @cbleek, I am working on this issue now

**Comment by TiSiE** [comment]
@kilip 
Things not working yet:

* Jobboard view does not display jobs from solr, but from the mongo database
* Also, no facets are displayed, nor the facet filter bar.
* In the JobBoardPaginationQueryFactory there's a call to ->getServiceLocator(), which leads to a
  deprecation warning.

reproducable on https://zf3.yawik.org/en/jobboard
Note that the solr module is indeed activated, but seems to not do anything....

**Comment by kilip** [comment]
@TiSiE 
I hope my #8 pull request can fix this issue.

**Comment by TiSiE** [comment]
I have the same issue in my development environment. I guess it happens, when using a Solr index that is NOT filled with local available jobs...
