### ISSUE TITLE
Test JobsPaginatorFactoryTest.php is failing

### ISSUE THREAD

**Issue by cbleek** [yawik/Solr#9]
https://travis-ci.org/yawik/Solr/builds/280462993#L1353

Solr\Paginator\JobsBoardPaginatorFactory::setCreationOptions() in /home/travis/build/yawik/yawik/module/Solr/test/SolrTest/Paginator/JobsPaginatorFactoryTest.php on line 88

**Comment by TiSiE** [comment]
Fixed in 5a4f8fa56d944492ca6df385ede9fceb82d57e60
